[package]
name = "humus"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
